services:
  nginx:
    image: nginx:latest
    container_name: proxy_nginx
    ports:
      - "727:727"
      - "777:777"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - main_web
      - sub_web
      - exploit_web
    networks:
      - webnet

  main_web:
    build: ./ 
    container_name: main_web
    expose:
      - "727"
    networks:
      - webnet

  sub_web:
    build: ./secret
    container_name: sub_web
    expose:
      - "727"
    networks:
      - webnet

  exploit_web:
    build: ./exploit
    container_name: exploit_web
    expose:
      - "777"
    networks:
      - webnet
