version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cds-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - cds-net

  sibling:
    build:
      context: ./sibling
    container_name: cds-sibling
    ports:
      - "5001:5000"
    networks:
      - cds-net

  bot:
    build:
      context: ./exploit-bot
    container_name: cds-bot
    # 외부에서도 호출해서 /visit, /logs 쓰고 싶다면 포트 공개
    ports:
      - "8000:8000"
    environment:
      - TARGET_ORIGIN=http://web:5000
      - ADMIN_USER=admin
      - ADMIN_PASS=temp
    networks:
      - cds-net

networks:
  cds-net:
    driver: bridge
