version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: proxy_nginx
    ports:
      - "727:727"
      - "777:777"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - main_web
      - sub_web
      - exploit_web

  main_web:
    build: ./
    container_name: main_web
    expose:
      - "727"

  secret_web:
    build: ./secret
    container_name: sub_web
    expose:
      - "727"

  exploit_web:
    build: ./exploit
    container_name: exploit_web
    expose:
      - "777"
