services:
  web:
    build: .
    container_name: main_web
    ports:
      - "727:727"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./instance:/app/instance 

  secret:
    build: ./secret
    container_name: secret_web
    ports:
      - "777:777"

  exploit:
    build: ./exploit      
    container_name: exploit_server
    ports:
      - "888:888"
    environment:
      - TARGET_ORIGIN=http://localhost:727
