version: "3"

services:
  web:
    build: .
    container_name: main_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  sibling:
    build: ./sibling
    container_name: sibling_web
    ports:
      - "5001:5001"

  exploit:
    build: ./exploit      # exploit 서버 코드가 들어 있는 디렉토리
    container_name: exploit_server
    ports:
      - "8000:8000"
    environment:
      - TARGET_ORIGIN=http://web:5000     # 공격자가 "관리자 브라우저"를 흉내낼 때 기준이 되는 도메인

depends_on:
  - web
