version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cds-web
    ports:
      - "5000:5000" # 호스트 5000 -> 컨테이너 9000
    environment:
      - FLASK_ENV=production
    networks:
      - cds-net

  sibling:
    build:
      context: ./sibling
    container_name: cds-sibling
    ports:
      - "5001:5001" # 호스트 5001 -> 컨테이너 6000
    volumes:
      - ./sibling/templates:/app/templates
    environment:
      - TARGET_ORIGIN=http://web:5000
      - ADMIN_USER=admin
      - ADMIN_PASS=temp
    networks:
      - cds-net

networks:
  cds-net:
    driver: bridge
