version: '3.9'

services:
  main:
    build: .
    container_name: cds-main
    ports:
      - "5000:5000" # 호스트 5000 -> 컨테이너 9000
    environment:
      - SECRET_KEY=supersecretkey
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - sibling

  sibling:
    build: ./sibling
    container_name: cds-sibling
    ports:
      - "5001:5001" # 호스트 5001 -> 컨테이너 6000
    volumes:
      - ./sibling/templates:/app/templates
    environment:
      - SECRET_KEY=siblingsecretkey
