services:
  web:
    build: .
    container_name: main_web
    ports:
      - "727:727"
    environment:
      - FLASK_ENV=development

  sibling:
    build: ./sibling
    container_name: sibling_web
    ports:
      - "777:777"

  exploit:
    build: ./exploit      
    container_name: exploit_server
    ports:
      - "888:888"
    environment:
      - TARGET_ORIGIN=http://web:727  
